#!/bin/bash

cd ${OPENSHIFT_REPO_DIR}
pip install -r requirements.txt --no-cache-dir

ln -sf $OPENSHIFT_DATA_DIR $OPENSHIFT_REPO_DIR/app/static/media
export MYSQL_USER=admintlFi1Gq
export MYSQL_PASSWORD=HEHdVn6lqugN
